### PR TITLE
Added 1 more question

### PR DESCRIPTION
**Pull request by kunalkumar007**
I have added 1 More question in #1 as the first step towards Hactoberfest 2021.

### CODE REVIEW

**Comment by yoobi** [comment]
Hello, the tag in the repo is mispelled 'hactoberfest' instead of 'hacktoberfest' don't forget to change it before accepting PR otherwise it won't count.

**Comment by KunalRaghav** [comment]
@yoobi Thanks made the changes

**Comment by kunalkumar007** [comment]
Hy @KunalRaghav, can you please review the PR and let me know if it is done.

**Comment by kunalkumar007** [comment]
I think now there is no need for this PR.🙂

**Pull request closed without merging**
